name: Deploy to GCP VM

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List repo files
      run: ls -R

    - name: Copy backend JAR to GCP VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        source: public
        target: /home/euser/maxx

    - name: Restart backend service
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          echo "jnani">>jnani
